stages:
  - code_quality
  - test
  - build
  
eslint:
  image: node:14.12.0
  stage: code_quality
  before_script:
    - npm install

testes:
  image: node:14.12.0
  stage: test
  before_script:
    - npm install
  script:
    - npm test
react_build:
  image: node:14.12.0
  stage: build
  before_script:
    - npm install
  script:
    - npm run-script build